name: Build/release

on:
  push:
    branches: [ master ]
    # tags:
    #   - 'v*.*.*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Build/release Electron app
        env:
          GH_TOKEN: ${{ secrets.gh_token }}
        run: |
          yarn install
          del .npmrc
          (Get-Content "node_modules/builder-util/out/util.js").Replace("^[\w","^[.\w")| out-file "node_modules/builder-util/out/util.js"
          yarn electron:build --publish always